language: python
python:
  - "3.6"

install:
  - pip install -r requirements_tests.txt
  - pip install coverage coveralls

script:
  - coverage run --source schemaflow -m unittest discover

after_success:
    - coveralls
